-- Requête 1 --
SELECT *
FROM OUVRAGES2
WHERE NBPAG > 500;

-- Requête 2 --
SELECT *
FROM PERSONNES2
WHERE SEXE='H'
AND VILLEPERS='Pau';

-- Requête 3 --
SELECT PRENOMPERS,NOMPERS
FROM PERSONNES2
WHERE VILLEPERS='Pau'
OR VILLEPERS='Lescar';

-- Requête 4 --
SELECT NOMPERS
FROM PERSONNES2,BIBLIOTHEQUES2
WHERE PERSONNES2.CODBIB = BIBLIOTHEQUES2.CODBIB
AND NOMBIB = 'Médiathèque André Labarrère';

-- Requête 5 --
SELECT DISTINCT NOMPERS,PRENOMPERS
FROM PERSONNES2 P,BIBLIOTHEQUES2 B,PRET2 PR,EXEMPLAIRES2 E, OUVRAGES2 O
WHERE PR.CODPERS = P.CODPERS
AND P.CODBIB = B.CODBIB
AND E.CODOUV = O.CODOUV
AND PRENOMAUT='George'
AND NOMAUT='Martin'
AND VILLEPERS = 'Pau'
OR VILLEPERS = 'Billère';

-- Requête 6 --
SELECT O.TITOUV,O.ANEDIT -- Ensemble des valeurs --
FROM OUVRAGES2 O,OUVRAGES2 O2
WHERE O.PRENOMAUT = O2.PRENOMAUT
AND O2.TITOUV = 'Le trone de fer, l''intégrale 1 : Le donjon rouge'; -- O2 contient uniquement cet ouvrage --

-- Requête 7 --
SELECT DISTINCT CODPERS,NOMPERS,PRENOMPERS,CPPERS,RUEPERS,VILLEPERS,SEXE,DNAISS,DATINSCRIPT,CODBIB
FROM PERSONNES2,OUVRAGES2
WHERE OUVRAGES2.ANEDIT > EXTRACT(YEAR from DNAISS)
AND TITOUV= 'Le trone de fer, l''intégrale 1 : Le donjon rouge';

-- Requête 8 --
SELECT CODPERS,NOMPERS,PRENOMPERS
FROM PERSONNES2 P
WHERE P.CODPERS NOT IN (	SELECT P2.CODPERS
							FROM PERSONNES2 P2,PRET2 PR,OUVRAGES2,EXEMPLAIRES2 E
							WHERE P2.CODPERS = PR.CODPERS
							AND E.CODOUV = OUVRAGES2.CODOUV
							AND PR.CODEX = E.CODEX
							AND OUVRAGES2.LANGUE = 'Anglais');

-- Requête 9 --
SELECT DISTINCT NOMPERS,PRENOMPERS
FROM PERSONNES2 P,PRET2 PR, OUVRAGES2 O, EXEMPLAIRES2 E
WHERE P.CODPERS = PR.CODPERS
AND E.CODOUV = O.CODOUV
AND PR.CODEX = E.CODEX
AND O.langue != 'Français';

-- Requête 10 --
SELECT DISTINCT TITOUV,NOMAUT,PRENOMAUT
FROM OUVRAGES2 O,EXEMPLAIRES2 E
WHERE O.CODOUV = E.CODOUV
AND ANEDIT + 1 = EXTRACT(YEAR from DATEENTBIB);

--Requête 11 --
--Plus tard--

-- III --
--Requête 1: Donnez le nombre de personnes habitant Pau ayant des prêts en cours --
SELECT COUNT(CODEX) AS NBEMPRUNTPAU
FROM PERSONNES2 P,PRET2 PR
WHERE PR.CODPERS = P.CODPERS
AND VILLEPERS = 'Pau';

--Requête 2: --
--Donnez les noms et prénoms des personnes qui n’ont aucun prêt en cours.--
SELECT CODPERS,NOMPERS, PRENOMPERS
FROM PERSONNES2 P
WHERE CODPERS NOT IN (	SELECT P2.CODPERS
						FROM PERSONNES2 P2, PRET2 PR
						WHERE PR.CODPERS = P2.CODPERS);

